language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# install: PLEASE CHANG ME
# DeltaBot doesn't need this right now

# command to run tests, e.g. python setup.py test
script:  ./runtests.sh